#!/bin/bash

# This script is shamelessly extended from https://github.com/saalfeldlab/n5-utils, thanks @axtimwalde & co!

THREADS="-1"
USERMEM="-1"

while [[ $# -gt 0 ]]; do
  case $1 in
    -t|--threads)
      THREADS="$2"
      shift # past argument
      shift # past value
      ;;
    -m|--mem)
      USERMEM="$2"
      shift # past argument
      shift # past value
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
  esac
done

if [ $THREADS == "-1" ]; then
  echo "Please define the number of threads for Java/Spark to use, e.g.: './install -t 8'. Stopping."
  exit 1
else
  echo "Spark number of threads: "$THREADS
fi

if [ $USERMEM == "-1" ]; then
  echo "You did not define the memory that Java/Spark can use, will be set automatically. You could do it by e.g.: './install -m 64' for 64GB of RAM"
fi


VERSION="0.0.2-SNAPSHOT"
INSTALL_DIR=$(pwd)
#INSTALL_DIR=${1:-$(pwd)}

echo ""
echo "Installing into $INSTALL_DIR (for local execution)"

if [ $USERMEM == "-1" ]; then
  # check for operating system
  if [[ "$OSTYPE" == "linux-gnu" ]]; then
    echo "Assuming on Linux operating system"
    MEM=$(cat /proc/meminfo | grep MemTotal | sed s/^MemTotal:\\\s*\\\|\\\s\\+[^\\\s]*$//g)
    MEMGB=$(($MEM/1024/1024))
    MEM=$((($MEMGB/5)*4))
  elif [[ "$OSTYPE" == "darwin"* ]]; then
    echo "Assuming on MacOS X operating system"
    # sysctl returns total hardware memory size in bytes
    MEM=$(sysctl hw.memsize | grep hw.memsize | sed s/hw.memsize://g)
    MEMGB=$(($MEM/1024/1024/1024))
    MEM=$((($MEMGB/5)*4))
  else
    echo "ERROR - Operating system (arg2) must be either linux or osx to determine max memory. Please specify max memory by e.g.: './install -m 64' for 64GB of RAM"
    exit
  fi

  echo "Available memory:" $MEMGB "GB, setting Java memory limit to" $MEM "GB"
else
  MEM=$USERMEM
  echo "Setting Java memory limit to" $MEM "GB"
fi

echo 'Building the code'

sleep 2

mvn clean install
#echo 'Building a farjar, which can also be used for cluster/cloud execution' 
#mvn clean install -P fatjar
mvn -Dmdep.outputFile=cp.txt -Dmdep.includeScope=runtime dependency:build-classpath

echo ""
echo "Installing 'affine-fusion' command into" $INSTALL_DIR

echo '#!/bin/bash' > affine-fusion
echo '' >> affine-fusion
echo "JAR=\$HOME/.m2/repository/net/preibisch/BigStitcher-Spark/${VERSION}/BigStitcher-Spark-${VERSION}.jar" >> affine-fusion
echo 'java \' >> affine-fusion
echo "  -Xmx${MEM}g -Dspark.master=local[${THREADS}] \\" >> affine-fusion
#echo '  -XX:+UseConcMarkSweepGC \' >> affine-fusion
echo -n '  -cp $JAR:' >> affine-fusion
echo -n $(cat cp.txt) >> affine-fusion
echo ' \' >> affine-fusion
echo '  net.preibisch.bigstitcher.spark.AffineFusion "$@"' >> affine-fusion

chmod a+x affine-fusion

if [ $(pwd) == "$INSTALL_DIR" ]; then
    echo "Installation directory equals current directory, we are done."
else
	echo "Creating directory $INSTALL_DIR and moving files..."
    mkdir -p $INSTALL_DIR
    mv affine-fusion $INSTALL_DIR/
fi

rm cp.txt

echo "Installation finished."
